"""Add season dates

Revision ID: 1d1914045664
Revises: d701116cee8e
Create Date: 2026-07-09 20:00:59.958911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1914045664'
down_revision: Union[str, Sequence[str], None] = 'd701116cee8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_seasons', sa.Column('start', sa.Date(), nullable=False))
    op.add_column('league_seasons', sa.Column('end', sa.Date(), nullable=False))
    op.add_column('league_seasons', sa.Column('current', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_seasons', 'current')
    op.drop_column('league_seasons', 'end')
    op.drop_column('league_seasons', 'start')
    # ### end Alembic commands ###
