"""Add venues

Revision ID: 396cfa6435c1
Revises: 1d1914045664
Create Date: 2026-07-09 21:25:44.642345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396cfa6435c1'
down_revision: Union[str, Sequence[str], None] = '1d1914045664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id')
    )
    op.add_column('teams', sa.Column('venue_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'teams', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'teams', type_='foreignkey') 
    op.drop_column('teams', 'venue_id')
    op.drop_table('venues')
    # ### end Alembic commands ###
