"""add standings table

Revision ID: 9753aea024ff
Revises: e95be2fb7900
Create Date: 2026-07-13 22:31:46.844175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9753aea024ff'
down_revision: Union[str, Sequence[str], None] = 'e95be2fb7900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('goals_diff', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('home_played', sa.Integer(), nullable=False),
    sa.Column('home_wins', sa.Integer(), nullable=False),
    sa.Column('home_draws', sa.Integer(), nullable=False),
    sa.Column('home_losses', sa.Integer(), nullable=False),
    sa.Column('home_goals_for', sa.Integer(), nullable=False),
    sa.Column('home_goals_against', sa.Integer(), nullable=False),
    sa.Column('away_played', sa.Integer(), nullable=False),
    sa.Column('away_wins', sa.Integer(), nullable=False),
    sa.Column('away_draws', sa.Integer(), nullable=False),
    sa.Column('away_losses', sa.Integer(), nullable=False),
    sa.Column('away_goals_for', sa.Integer(), nullable=False),
    sa.Column('away_goals_against', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_season_id', 'team_id', name='uq_standing_league_season_team')
    )
    op.create_index(op.f('ix_standings_league_season_id'), 'standings', ['league_season_id'], unique=False)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_league_season_id'), table_name='standings')
    op.drop_table('standings')
    # ### end Alembic commands ###
