"""Add fixtures

Revision ID: a0d5a2862964
Revises: 396cfa6435c1
Create Date: 2026-07-13 06:26:17.589273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d5a2862964'
down_revision: Union[str, Sequence[str], None] = '396cfa6435c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('league_season_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('round', sa.String(length=100), nullable=False),
    sa.Column('referee', sa.String(length=255), nullable=True),
    sa.Column('status_short', sa.String(length=20), nullable=False),
    sa.Column('status_long', sa.String(length=100), nullable=False),
    sa.Column('elapsed', sa.Integer(), nullable=True),
    sa.Column('extra_time', sa.Integer(), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('halftime_home', sa.Integer(), nullable=True),
    sa.Column('halftime_away', sa.Integer(), nullable=True),
    sa.Column('fulltime_home', sa.Integer(), nullable=True),
    sa.Column('fulltime_away', sa.Integer(), nullable=True),
    sa.Column('extratime_home', sa.Integer(), nullable=True),
    sa.Column('extratime_away', sa.Integer(), nullable=True),
    sa.Column('penalty_home', sa.Integer(), nullable=True),
    sa.Column('penalty_away', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_api_id'), 'fixtures', ['api_id'], unique=True)
    op.create_index(op.f('ix_fixtures_away_team_id'), 'fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_home_team_id'), 'fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_kickoff'), 'fixtures', ['kickoff'], unique=False)
    op.create_index(op.f('ix_fixtures_league_season_id'), 'fixtures', ['league_season_id'], unique=False)
    with op.batch_alter_table("teams") as batch_op:
        batch_op.create_foreign_key(
            "fk_teams_venue_id",
            "venues",
            ["venue_id"],
            ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams") as batch_op:
        batch_op.drop_constraint(
            "fk_teams_venue_id",
            type_="foreignkey",
    )
    op.drop_index(op.f('ix_fixtures_league_season_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_kickoff'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_api_id'), table_name='fixtures')
    op.drop_table('fixtures')
    # ### end Alembic commands ###
