"""add players table

Revision ID: aa4c5bcd19d4
Revises: 9753aea024ff
Create Date: 2026-07-18 20:59:58.958798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4c5bcd19d4'
down_revision: Union[str, Sequence[str], None] = '9753aea024ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=False),
    sa.Column('birth_country', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('height', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=False),
    sa.Column('is_injured', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_api_id'), 'players', ['api_id'], unique=True)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_api_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
